"""create initial ynab schema

Revision ID: 794607ba49dc
Revises: 
Create Date: 2026-05-19 16:50:08.181523
"""

from alembic import op
import sqlalchemy as sa


revision = '794607ba49dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('on_budget', sa.Boolean(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('cleared_balance', sa.BigInteger(), nullable=True),
    sa.Column('uncleared_balance', sa.BigInteger(), nullable=True),
    sa.Column('transfer_payee_id', sa.String(length=64), nullable=True),
    sa.Column('direct_import_linked', sa.Boolean(), nullable=True),
    sa.Column('direct_import_in_error', sa.Boolean(), nullable=True),
    sa.Column('last_reconciled_at', sa.String(length=64), nullable=True),
    sa.Column('debt_original_balance', sa.BigInteger(), nullable=True),
    sa.Column('debt_interest_rates', sa.Text(), nullable=True),
    sa.Column('debt_minimum_payments', sa.Text(), nullable=True),
    sa.Column('debt_escrow_amounts', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_budget_id'), 'accounts', ['budget_id'], unique=False)
    op.create_table('budget_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_changes_action'), 'budget_changes', ['action'], unique=False)
    op.create_index(op.f('ix_budget_changes_batch_id'), 'budget_changes', ['batch_id'], unique=False)
    op.create_index(op.f('ix_budget_changes_budget_id'), 'budget_changes', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_changes_entity_id'), 'budget_changes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_budget_changes_recorded_at'), 'budget_changes', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_budget_changes_resource'), 'budget_changes', ['resource'], unique=False)
    op.create_table('budget_months',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('income', sa.BigInteger(), nullable=True),
    sa.Column('budgeted', sa.BigInteger(), nullable=True),
    sa.Column('activity', sa.BigInteger(), nullable=True),
    sa.Column('to_be_budgeted', sa.BigInteger(), nullable=True),
    sa.Column('age_of_money', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_months_budget_id'), 'budget_months', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_months_month'), 'budget_months', ['month'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_month', sa.String(length=10), nullable=True),
    sa.Column('last_month', sa.String(length=10), nullable=True),
    sa.Column('last_modified_on', sa.String(length=64), nullable=True),
    sa.Column('date_format', sa.String(length=64), nullable=True),
    sa.Column('currency_format_iso_code', sa.String(length=16), nullable=True),
    sa.Column('currency_format_example', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('category_group_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('original_category_group_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('budgeted', sa.BigInteger(), nullable=True),
    sa.Column('activity', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('goal_type', sa.String(length=64), nullable=True),
    sa.Column('goal_needs_whole_amount', sa.Boolean(), nullable=True),
    sa.Column('goal_day', sa.BigInteger(), nullable=True),
    sa.Column('goal_cadence', sa.BigInteger(), nullable=True),
    sa.Column('goal_cadence_frequency', sa.BigInteger(), nullable=True),
    sa.Column('goal_creation_month', sa.String(length=10), nullable=True),
    sa.Column('goal_target', sa.BigInteger(), nullable=True),
    sa.Column('goal_target_month', sa.String(length=10), nullable=True),
    sa.Column('goal_percentage_complete', sa.BigInteger(), nullable=True),
    sa.Column('goal_months_to_budget', sa.BigInteger(), nullable=True),
    sa.Column('goal_under_funded', sa.BigInteger(), nullable=True),
    sa.Column('goal_overall_funded', sa.BigInteger(), nullable=True),
    sa.Column('goal_overall_left', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_budget_id'), 'categories', ['budget_id'], unique=False)
    op.create_index(op.f('ix_categories_category_group_id'), 'categories', ['category_group_id'], unique=False)
    op.create_table('category_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_groups_budget_id'), 'category_groups', ['budget_id'], unique=False)
    op.create_table('month_categories',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('budgeted', sa.BigInteger(), nullable=True),
    sa.Column('activity', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_month_categories_budget_id'), 'month_categories', ['budget_id'], unique=False)
    op.create_index(op.f('ix_month_categories_category_id'), 'month_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_month_categories_month'), 'month_categories', ['month'], unique=False)
    op.create_table('payee_locations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('payee_id', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payee_locations_budget_id'), 'payee_locations', ['budget_id'], unique=False)
    op.create_index(op.f('ix_payee_locations_payee_id'), 'payee_locations', ['payee_id'], unique=False)
    op.create_table('payees',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('transfer_account_id', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payees_budget_id'), 'payees', ['budget_id'], unique=False)
    op.create_table('scheduled_transactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('payee_id', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('transfer_account_id', sa.String(length=64), nullable=True),
    sa.Column('date_first', sa.String(length=10), nullable=True),
    sa.Column('date_next', sa.String(length=10), nullable=True),
    sa.Column('frequency', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('flag_color', sa.String(length=32), nullable=True),
    sa.Column('flag_name', sa.String(length=255), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_transactions_budget_id'), 'scheduled_transactions', ['budget_id'], unique=False)
    op.create_table('subtransactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('payee_id', sa.String(length=64), nullable=True),
    sa.Column('payee_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('transfer_account_id', sa.String(length=64), nullable=True),
    sa.Column('transfer_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtransactions_budget_id'), 'subtransactions', ['budget_id'], unique=False)
    op.create_index(op.f('ix_subtransactions_transaction_id'), 'subtransactions', ['transaction_id'], unique=False)
    op.create_table('sync_state',
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('server_knowledge', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('budget_id', 'resource')
    )
    op.create_table('transaction_notifications',
    sa.Column('transaction_id', sa.String(length=64), nullable=False),
    sa.Column('notified_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('budget_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('payee_id', sa.String(length=64), nullable=True),
    sa.Column('transfer_account_id', sa.String(length=64), nullable=True),
    sa.Column('transfer_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('matched_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('import_id', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('cleared', sa.String(length=32), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('flag_color', sa.String(length=32), nullable=True),
    sa.Column('flag_name', sa.String(length=255), nullable=True),
    sa.Column('foreign_amount', sa.BigInteger(), nullable=True),
    sa.Column('foreign_currency_code', sa.String(length=16), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_budget_id'), 'transactions', ['budget_id'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_payee_id'), 'transactions', ['payee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_payee_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_budget_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('transaction_notifications')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_subtransactions_transaction_id'), table_name='subtransactions')
    op.drop_index(op.f('ix_subtransactions_budget_id'), table_name='subtransactions')
    op.drop_table('subtransactions')
    op.drop_index(op.f('ix_scheduled_transactions_budget_id'), table_name='scheduled_transactions')
    op.drop_table('scheduled_transactions')
    op.drop_index(op.f('ix_payees_budget_id'), table_name='payees')
    op.drop_table('payees')
    op.drop_index(op.f('ix_payee_locations_payee_id'), table_name='payee_locations')
    op.drop_index(op.f('ix_payee_locations_budget_id'), table_name='payee_locations')
    op.drop_table('payee_locations')
    op.drop_index(op.f('ix_month_categories_month'), table_name='month_categories')
    op.drop_index(op.f('ix_month_categories_category_id'), table_name='month_categories')
    op.drop_index(op.f('ix_month_categories_budget_id'), table_name='month_categories')
    op.drop_table('month_categories')
    op.drop_index(op.f('ix_category_groups_budget_id'), table_name='category_groups')
    op.drop_table('category_groups')
    op.drop_index(op.f('ix_categories_category_group_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_budget_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_budget_months_month'), table_name='budget_months')
    op.drop_index(op.f('ix_budget_months_budget_id'), table_name='budget_months')
    op.drop_table('budget_months')
    op.drop_index(op.f('ix_budget_changes_resource'), table_name='budget_changes')
    op.drop_index(op.f('ix_budget_changes_recorded_at'), table_name='budget_changes')
    op.drop_index(op.f('ix_budget_changes_entity_id'), table_name='budget_changes')
    op.drop_index(op.f('ix_budget_changes_budget_id'), table_name='budget_changes')
    op.drop_index(op.f('ix_budget_changes_batch_id'), table_name='budget_changes')
    op.drop_index(op.f('ix_budget_changes_action'), table_name='budget_changes')
    op.drop_table('budget_changes')
    op.drop_index(op.f('ix_accounts_budget_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
